[tools]
aws-cli = "latest"
aws-sso = "latest"
bat = "latest"
go = "latest"
gum = "latest"
"cargo:https://github.com/helix-editor/helix" = { version = "branch:master", crate = "helix-term" }
ghcup = "latest"
jq = "latest"
ripgrep = "latest"
rust = "latest"
starship = "latest"
tfenv = "latest"
yq = "latest"
just = "latest"
zoxide = "latest"
uv = "latest"
zellij = "latest"
glow = "latest"
node = "latest"
bun = "latest"
xh = "latest"
gitui = "latest"
dust = "latest"
yazi = "latest"
ripgrep-all = "latest"
mask = "latest"
mprocs = "latest"
aichat = "latest"
"aqua:neovim/neovim" = "latest"
peco = "latest"
gleam = "latest"
"go:github.com/callumalpass/handwrite" = "latest"
"cargo:gittype" = "latest"
"cargo:basalt-tui" = "latest"
"cargo:https://github.com/Zheoni/cooklang-chef" = "latest"
bat-extras = "latest"
java = "latest"
1password = "latest"
opencode = "latest"
lua = "latest"
jj = "latest"
jjui = "latest"
"go:golang.org/x/tools/gopls" = "latest"
kubectl = "latest"
babashka = "latest"
clojure = "latest"
helm = "latest"
kubectx = "latest"
kubens = "latest"
typst = "latest"
"cargo:alecthomas/t" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["terraform"]
experimental = true
