[[language]]
name = "pencil"
scope = "source.pencil"
injection-regex = "pencil"
file-types = ["pncl"]
comment-tokens = "//"
block-comment-tokens = { start = "/*", end = "*/" }
indent = { tab-width = 4, unit = "    " }

[[grammar]]
name = "pencil"
source = { path = "/Users/dorseyj/Documents/co/languages/pencil/tree-sitter-pencil" }

[language-servier.mdbase-lsp]
command = "mdbase-lsp"

[[language]]
name = "markdown"
scope = "source.md"
injection-regex = "md|markdown"
file-types = ["md", "livemd", "markdown", "mdx", "mkd", "mkdn", "mdwn", "mdown", "markdn", "mdtxt", "mdtext", "workbook", { glob = "PULLREQ_EDITMSG" }]
roots = [".marksman.toml"]
language-servers = ["marksman", "markdown-oxide", "rumdl", "mdbase-lsp" ]
indent = { tab-width = 2, unit = "  " }
block-comment-tokens = { start = "<!--", end = "-->" }
word-completion.trigger-length = 4
